export enum Api {
  getMenuList = '/api/sysUser/getMenuList',
  getDeptList = '/api/department/list',
  getImg = "/api/sysUser/image",
  login = "/api/user/login",
  getInfo = '/api/sysUser/getInfo',
  getParent = "/api/department/parent",
  add = "/api/department",
  delete = "/api/department",
  getUserList = "/api/user/list",
  addEditUser = "/api/user",
  getRoleList = "api/role/list",
  addRole = "/api/role",
  assignTree = '/api/role/getAssignPermissionTree',
  assignSave = '/api/role/roleAssignSave',
  getMenuTable = "/api/menu/list",
  getMenuParent = "/api/menu/parent",
  addMenu = "/api/menu",
  getRoleId = '/api/user/getRoleIdByUserId',
  assingRole = "/api/user/assingRole",
  loginOut = '/api/sysUser/loginOut',
  restore = '/api/backup/restore'
} 